name: Build and Release Book

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            latexmk xetex fontspec titlesec setspace microtype parskip xcolor tocloft geometry kvoptions ltxcmds kvsetkeys mdframed zref needspace hyperref fancyhdr

      - name: Install Pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: '3.5'

      - name: Install system fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-roboto

      - name: Compile LaTeX to PDF with XeLaTeX
        run: |
          export PATH="/home/runner/work/_temp/setup-texlive-action/2024/bin/x86_64-linux:$PATH"
          latexmk -pdf -xelatex -interaction=nonstopmode -f book_wmd_to_glitch.tex
        
      - name: Generate HTML with Pandoc
        run: |
          pandoc -s book_wmd_to_glitch.tex -o book_wmd_to_glitch-${{ github.ref_name }}.html

      - name: Generate EPUB with Pandoc
        run: |
          pandoc -s book_wmd_to_glitch.tex -o book_wmd_to_glitch-${{ github.ref_name }}.epub

      - name: Generate FB2 with Pandoc
        run: |
          pandoc -s book_wmd_to_glitch.tex -o book_wmd_to_glitch-${{ github.ref_name }}.fb2

      - name: Install Calibre
        run: |
          sudo apt-get update
          sudo apt-get install -y calibre

      - name: Convert EPUB to MOBI
        run: |
          ebook-convert book_wmd_to_glitch-${{ github.ref_name }}.epub book_wmd_to_glitch-${{ github.ref_name }}.mobi

      - name: Rename HTML to index.html for GitHub Pages
        run: |
          mv book_wmd_to_glitch-${{ github.ref_name }}.html index.html

      - name: Deploy HTML to GitHub Pages
        continue-on-error: true  # Makes this step optional; workflow continues even if it fails
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true
          destination_dir: .
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy index.html to GitHub Pages for ${{ github.ref_name }}'

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            book_wmd_to_glitch.pdf
            book_wmd_to_glitch-${{ github.ref_name }}.html
            book_wmd_to_glitch-${{ github.ref_name }}.epub
            book_wmd_to_glitch-${{ github.ref_name }}.fb2
            book_wmd_to_glitch-${{ github.ref_name }}.mobi