name: Build and Release Book

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            latexmk xetex fontspec titlesec setspace microtype parskip xcolor tocloft liberation geometry kvoptions

      - name: Verify XeLaTeX and Packages Installation
        run: |
          which xelatex || echo "XeLaTeX not found!"
          xelatex --version
          kpsewhich geometry.sty || echo "geometry.sty not found!"
          kpsewhich xcolor.sty || echo "xcolor.sty not found!"
          kpsewhich fontspec.sty || echo "fontspec.sty not found!"

      - name: Show book_wmd_to_glitch.tex
        run: cat book_wmd_to_glitch.tex

      - name: Compile LaTeX to PDF with XeLaTeX
        run: |
          latexmk -xelatex -interaction=nonstopmode -f book_wmd_to_glitch.tex

      - name: Generate HTML with Pandoc
        run: |
          pandoc -s book_wmd_to_glitch.tex -o book_wmd_to_glitch-${{ github.ref_name }}.html

      - name: Generate EPUB with Pandoc
        run: |
          pandoc -s book_wmd_to_glitch.tex -o book_wmd_to_glitch-${{ github.ref_name }}.epub

      - name: Generate FB2 with Pandoc
        run: |
          pandoc -s book_wmd_to_glitch.tex -o book_wmd_to_glitch-${{ github.ref_name }}.fb2

      - name: Install Calibre
        run: |
          sudo apt-get update
          sudo apt-get install -y calibre

      - name: Convert EPUB to MOBI
        run: |
          ebook-convert book_wmd_to_glitch-${{ github.ref_name }}.epub book_wmd_to_glitch-${{ github.ref_name }}.mobi

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            book_wmd_to_glitch.pdf
            book_wmd_to_glitch-${{ github.ref_name }}.html
            book_wmd_to_glitch-${{ github.ref_name }}.epub
            book_wmd_to_glitch-${{ github.ref_name }}.fb2
            book_wmd_to_glitch-${{ github.ref_name }}.mobi