name: Build and Release Book

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create main.tex
        run: |
          echo "\\documentclass{book}" > main.tex
          echo "\\begin{document}" >> main.tex
          for file in book-part*.tex; do
            echo "\\input{\${file%.tex}}" >> main.tex
          done
          echo "\\end{document}" >> main.tex

      - name: Setup TeXLive
        uses: ./.github/actions/setup-texlive
        with:
          requirements-file: '.github/texlive/requirements.txt'

      - name: Compile LaTeX to PDF
        run: |
          latexmk -pdf main.tex
          mv main.pdf book.pdf

      - name: Generate HTML with Pandoc
        run: |
          pandoc -s main.tex -o book.html

      - name: Generate EPUB with Pandoc
        run: |
          pandoc -s main.tex -o book.epub

      - name: Generate FB2 with Pandoc
        run: |
          pandoc -s main.tex -o book.fb2

      - name: Install Calibre
        run: |
          sudo apt-get update
          sudo apt-get install -y calibre

      - name: Convert EPUB to MOBI
        run: |
          ebook-convert book.epub book.mobi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: book.pdf
          asset_name: book.pdf
          asset_content_type: application/pdf

      - name: Upload HTML
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: book.html
          asset_name: book.html
          asset_content_type: text/html

      - name: Upload EPUB
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: book.epub
          asset_name: book.epub
          asset_content_type: application/epub+zip

      - name: Upload FB2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: book.fb2
          asset_name: book.fb2
          asset_content_type: application/x-fictionbook+xml

      - name: Upload MOBI
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: book.mobi
          asset_name: book.mobi
          asset_content_type: application/x-mobipocket-ebook